window.oneSevillaMenuRange = "28 septiembre–4 octubre";
window.oneSevillaWeekOrder = [1, 2, 3, 4, 5, 6, 0];
window.oneSevillaWeeklyMenu = {
  1: { day: "Lunes 28", lunch: ["Fabada asturiana", "Picadillo de atún", "Salchichas frescas a la plancha", "Salmón en salsa Thai", "Puré de patatas", "Calabacín con reducción de soja", "Fruta fresca y lácteo"], dinner: ["Patatas cheese bacon", "Ensalada César", "Croquetas de cocido", "Merluza a la plancha", "Coditos salteados", "Coliflor en tempura", "Fruta fresca y lácteo"] },
  2: { day: "Martes 29", lunch: ["Arroz con tomate", "Garbanzos al curry", "Chuleta a la plancha", "Bonito encebollado", "Patatas a lo pobre", "Zanahoria al vapor con cebolla", "Fruta fresca y lácteo"], dinner: ["Macarrones gratinados con atún", "Sopa de ave con fideos", "Jamoncitos de pollo en salsa barbacoa", "Tortilla de jamón york", "Berenjenas con miel", "Pimientos verdes a la plancha", "Fruta fresca y lácteo"] },
  3: { day: "Miércoles 30", lunch: ["Hojaldre de salmón, queso y cebolla caramelizada casera", "Pastel de carne", "Rabas de calamar rebozadas", "Magro de cerdo en salsa", "Arroz cajón", "Tomate a la provenzal", "Fruta fresca y lácteo"], dinner: ["Ensalada de pollo a la barbacoa", "Tallarines con nata y champiñones", "Wrap de pollo", "Abadejo a la plancha", "Nachos", "Habitas baby con pimentón", "Fruta fresca y lácteo"] },
  4: { day: "Jueves 1 oct", lunch: ["Fideuá de carne", "Gazpacho andaluz", "Tortilla de patatas", "Bacalao al pil pil", "Brócoli salteado", "Pimientos morrones salteados", "Fruta fresca y lácteo"], dinner: ["Crema de hortalizas", "Ensalada caprese", "Panini 4 estaciones", "Empanada de atún", "Fetuccini de espinacas", "Maíz especiado", "Fruta fresca y lácteo"] },
  5: { day: "Viernes 2 oct", lunch: ["Lentejas con chorizo", "Ensalada de lechuga, col y pepino", "Escalope de pollo empanado", "Boquerones en tempura", "Patatas julianas", "Espárragos verdes a la plancha", "Fruta fresca y lácteo"], dinner: ["Fiesta de bienvenida · barbacoa"] },
  6: { day: "Sábado 3 oct", lunch: ["Lasaña de carne", "Patatas aliñadas", "Albóndigas en salsa", "Gallineta a la vizcaína", "Patatas risoladas", "Cous cous con frutos secos", "Fruta fresca y lácteo"], dinner: ["Judías verdes salteadas", "Ensalada mediterránea", "Flamenquín de pollo", "Palometa al horno", "Patatas deluxe", "Tomate al horno", "Fruta fresca y lácteo"] },
  0: { day: "Domingo 4 oct", lunch: ["Arroz al horno", "Tomate aliñado", "Pollo asado en su jugo", "Fogonero a la plancha", "Guisantes salteados", "Champiñones al ajillo", "Fruta fresca y lácteo"], dinner: ["Pasta con tomate", "Verduras asadas", "Pizza mediterránea", "Merluza al ajillo", "Patatas chips", "Wok de verdura", "Fruta fresca y lácteo"] }
};
