window.oneSevillaMenuRange = "5–11 octubre";
window.oneSevillaWeekOrder = [1, 2, 3, 4, 5, 6, 0];
window.oneSevillaWeeklyMenu = {
  1: { day: "Lunes 5", lunch: ["Canelones de pollo", "Potaje de garbanzos", "Contramuslo de pollo en salsa teriyaki", "Bonito al pimentón", "Champiñones al ajillo", "Salteado campestre", "Fruta fresca y lácteo"], dinner: ["Crema de hortalizas", "Pisto con huevo", "Cinta de lomo al horno en salsa barbacoa", "Fogonero al horno", "Tallarines al ajo", "Brócoli salteado", "Fruta fresca y lácteo"] },
  2: { day: "Martes 6", lunch: ["Arroz negro con alioli", "Salpicón de marisco", "Carrillada en salsa", "Gallo al horno", "Patatas steakhouse", "Calabaza al horno", "Fruta fresca y lácteo"], dinner: ["Revuelto de ajetes", "Espirales con soja", "Pavo a la plancha", "Atún con tomate", "Coliflor rebozada", "Puré de patatas", "Fruta fresca y lácteo"] },
  3: { day: "Miércoles 7", lunch: ["Tortellini napolitana", "Ensalada mixta", "Jamoncitos de pollo en salsa", "Merluza a la plancha", "Verduras en tempura", "Zanahoria salteada", "Fruta fresca y lácteo"], dinner: ["Patatas cheese bacon", "Panaché de verduras", "Empanadillas de atún", "Tortilla de patatas y calabacín", "Pimientos asados al horno", "Tomate a la provenzal", "Noche de postres caseros"] },
  4: { day: "Jueves 8", lunch: ["Hojaldre de pollo a la barbacoa", "Puchero", "Albóndigas en amarillo", "Bacalao al pil pil", "Guisantes salteados", "Alcachofas con pimentón", "Fruta fresca y lácteo"], dinner: ["Ensalada de patatas con mahonesa, huevo y atún", "Crema de calabaza", "Fajitas de pollo", "Jurel a la plancha", "Nachos", "Espárragos a la plancha", "Fruta fresca y lácteo"] },
  5: { day: "Viernes 9", lunch: ["Arroz con carne", "Salmorejo con huevo y jamón", "Huevos fritos con chorizo", "Tortillitas de camarones", "Patatas fritas", "Judías al horno con cebolla al vapor", "Fruta fresca y lácteo"], dinner: ["Ensalada de pasta", "Sopa castellana", "Filete de jamón a la plancha", "Salmón a la plancha", "Aritos de cebolla", "Calabacín a la plancha", "Fruta fresca y lácteo"] },
  6: { day: "Sábado 10", lunch: ["Patatas con choco", "Crema de puerros", "Nuggets de pollo", "Gallineta a la roteña", "Berenjenas rebozadas", "Pimientos del padrón fritos", "Fruta fresca y lácteo"], dinner: ["Ensalada César", "Arroz salteado con champiñones", "Croquetas de cocido", "Tortilla francesa", "Tomate aliñado", "Verduras al grill", "Fruta fresca y lácteo"] },
  0: { day: "Domingo 11", lunch: ["Pastel de carne", "Picadillo de atún", "Chuletas en salsa", "Abadejo a la plancha", "Trigo Ebly con frutos secos", "Espárragos a la plancha", "Fruta fresca y lácteo"], dinner: ["Sopa de pescado", "Espaguetis con tomate", "Hot dog completo", "Dorado al horno", "Patatas chips", "Verduras asadas", "Fruta fresca y lácteo"] }
};
